name: Android Pull Request & Master CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Android Lint
        run: ./gradlew lint
      - name: Run Android Lint Reporter to report Lint and Detekt result to PR
        uses: ./
        with:
          report-path: ${{ github.workspace }}/__tests__/resource/lint-results.xml
          continue-on-error: true
