name: Android Pull Request & Master CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-18.04

    steps:
      - name: "Say Hello Mona it's Monday"
          run: echo "Greeting first_Name. Today is $DAY_OF_WEEK!"