name: Android Pull Request & Master CI

on:
  pull_request:
    paths:
      - .github/workflows/android-lint.yml
      - '*/src/**'
      - gradle/**
      - '**.gradle'
      - gradle.properties
      - gradlew*

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
      - name: setup JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8
      - name: Run Android Linter
        run: ./gradlew lint
      - name: report
        uses: yutailang0119/action-android-lint@v3
        with:
          report-path: build/reports/*.xml
         continue-on-error: false
