name: Android Pull Request & Master CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
  issues:
    types: [ opened ]
    pull_request:
      types: [ opened ]
    project_card:
      types: [ moved ]
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: "triage"
          repo-token: ${{ secrets.GITHUB_TOKEN }}