name: Android Pull Request & Master CI

on:
  pull_request:
    paths:
      - .github/workflows/android-lint.yml
      - '*/src/**'
      - gradle/**
      - '**.gradle'
      - gradle.properties
      - gradlew*

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
      - name: Run Android Linter
        run: ./gradlew lint
