# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
  push:
    branches:
      - master


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  testing:
    name: Lint Check and Testing

    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Step 3: Check the code with Android linter
      - name: Run Android Linter
        run: ./gradlew lint
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: app/chau.html